#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

# If you want to allow non-Able to true.

# Redirect output to stderr.

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
	# Note that the use of brackets around a tr range is ok here, (it's
	# even required, for portability to Solaris 10's /usr/bin/tr), since
	# the square bracket bytes happen to fall in the 
read -p "Enregistrer la date du commit (y/[n]) ?" yn < /dev/tty
yn=${yn:n}
case $yn in
 [Yy]* )
git log --format="%h: %cd"  -n 1 >> suivi/SuiviDate.txt
echo "date sauvegarder dans /suivi/CommitInfo.txt"
 exit 0;;
 [Nn]* )
 exit 0;;
esac
exit 0



# If there are whitespace errors, print the offending file names and fail.


# If there are whitespace errors, print the offending file names and fail.

